-- 0001_init.sql
--
-- The initial schema, generated by running AutoMigrate against a scratch
-- PostgreSQL 16 and dumping the result. It is checked in rather than derived at
-- runtime because AutoMigrate never drops or renames: it silently diverges from
-- what the code expects, which is why config refuses DB_AUTO_MIGRATE in
-- production.
--
-- gen_random_uuid() is a core function from PostgreSQL 13 onward, so no
-- extension is required. psql meta-commands emitted by pg_dump (\restrict,
-- \connect) are stripped: they are not SQL and the driver rejects them.

--
-- PostgreSQL database dump
--

--
-- Name: banners; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.banners (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    photo character varying(255),
    photo_public_id character varying(255),
    name character varying(255) NOT NULL,
    description text,
    status bigint NOT NULL,
    user_id uuid,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone
);

--
-- Name: cart_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cart_items (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    cart_id uuid,
    product_id uuid,
    selected boolean,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone
);

--
-- Name: carts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.carts (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid,
    shop_id uuid,
    status bigint DEFAULT 0,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone
);

--
-- Name: customer_addresses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer_addresses (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    label character varying(100) NOT NULL,
    address_text text NOT NULL,
    lat numeric NOT NULL,
    lng numeric NOT NULL,
    is_default boolean DEFAULT false,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone
);

--
-- Name: event_bundle_buys; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.event_bundle_buys (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    event_id uuid NOT NULL,
    product_id uuid NOT NULL,
    quantity bigint NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone
);

--
-- Name: event_bundle_rewards; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.event_bundle_rewards (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    event_id uuid NOT NULL,
    product_id uuid NOT NULL,
    quantity bigint NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone
);

--
-- Name: event_products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.event_products (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    event_id uuid NOT NULL,
    product_id uuid NOT NULL,
    discount_percent bigint,
    discount_amount numeric,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone
);

--
-- Name: events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.events (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying(255) NOT NULL,
    type_event character varying(100),
    start_date timestamp without time zone,
    end_date timestamp without time zone,
    cover character varying(255),
    cover_public_id character varying(255),
    status bigint DEFAULT 0,
    created_by uuid,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone
);

--
-- Name: favorite_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.favorite_items (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    favorite_id uuid,
    product_id uuid,
    selected boolean,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone
);

--
-- Name: favorites; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.favorites (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone
);

--
-- Name: images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.images (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    image_path character varying(255),
    public_id character varying(255),
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone
);

--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    channel character varying(20) NOT NULL,
    title character varying(255) NOT NULL,
    body text,
    type character varying(30) DEFAULT 'INFO'::character varying,
    reference_id uuid,
    target_type character varying(30),
    target_route character varying(255),
    read_at timestamp with time zone,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone
);

--
-- Name: order_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_events (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    order_id uuid,
    event_id uuid,
    type character varying(100),
    discount numeric,
    created_at timestamp with time zone,
    updated_at timestamp with time zone
);

--
-- Name: order_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_items (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    order_id uuid,
    product_id uuid,
    quantity bigint,
    sub_total numeric,
    created_at timestamp with time zone,
    updated_at timestamp with time zone
);

--
-- Name: order_rewards; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_rewards (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    order_id uuid,
    product_id uuid,
    quantity bigint,
    created_at timestamp with time zone,
    updated_at timestamp with time zone
);

--
-- Name: order_vouchers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_vouchers (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    order_id uuid,
    voucher_id uuid,
    created_at timestamp with time zone,
    updated_at timestamp with time zone
);

--
-- Name: orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.orders (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    code character varying(255),
    user_id uuid,
    shop_id uuid,
    cart_id uuid,
    status character varying(255),
    order_type character varying(255),
    payment_method character varying(255),
    sub_total numeric,
    discount_event numeric,
    discount_voucher numeric,
    shipping_fee numeric,
    total numeric,
    customer_address_id uuid,
    note text,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone
);

--
-- Name: product_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_images (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    product_id uuid,
    image_id uuid,
    alt_text character varying(255),
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone
);

--
-- Name: products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.products (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying(255),
    image_id uuid,
    code character varying(255),
    price bigint,
    unit character varying(50),
    description text,
    status bigint DEFAULT 0,
    type_product_id uuid,
    created_by uuid,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone
);

--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying(100) NOT NULL
);

--
-- Name: shop_cashiers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.shop_cashiers (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    shop_id uuid NOT NULL,
    cashier_id uuid NOT NULL,
    assigned_at timestamp with time zone DEFAULT now(),
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone
);

--
-- Name: shop_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.shop_images (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    shop_id uuid NOT NULL,
    image_id uuid NOT NULL,
    altext character varying(255) NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone
);

--
-- Name: shop_products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.shop_products (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    shop_id uuid NOT NULL,
    product_id uuid NOT NULL,
    price numeric(12,2),
    stock bigint DEFAULT 0,
    status bigint DEFAULT 0,
    assigned_at timestamp with time zone DEFAULT now(),
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone
);

--
-- Name: shops; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.shops (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying(255) NOT NULL,
    cover character varying(255) NOT NULL,
    cover_public_id character varying(255),
    description text,
    full_address character varying(255),
    lat numeric(10,8),
    lng numeric(11,8),
    status bigint DEFAULT 0,
    created_by uuid,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone
);

--
-- Name: type_products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.type_products (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    image character varying(255),
    image_public_id character varying(255),
    name character varying(255) NOT NULL,
    status bigint NOT NULL,
    user_id uuid,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone
);

--
-- Name: user_identities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_identities (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    provider character varying(32) NOT NULL,
    subject character varying(255) NOT NULL,
    email character varying(255),
    last_login_at timestamp with time zone,
    created_at timestamp with time zone,
    updated_at timestamp with time zone
);

--
-- Name: user_point_histories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_point_histories (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid,
    point_type character varying(100),
    source character varying(255),
    source_id character varying(255),
    points bigint,
    expired_at timestamp without time zone,
    description text,
    direction character varying(100),
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    CONSTRAINT chk_user_point_histories_direction CHECK (((direction)::text = ANY ((ARRAY['in'::character varying, 'out'::character varying])::text[])))
);

--
-- Name: user_points; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_points (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid,
    total_points bigint,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone
);

--
-- Name: user_voucher_details; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_voucher_details (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    voucher_code character varying(50) NOT NULL,
    discount_type character varying(100) NOT NULL,
    discount_amount bigint NOT NULL,
    discount_percent bigint NOT NULL,
    min_purchase_amount bigint NOT NULL,
    valid_from timestamp with time zone,
    valid_until timestamp with time zone,
    description text,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone
);

--
-- Name: user_vouchers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_vouchers (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid,
    voucher_id uuid,
    detail_id uuid,
    is_used boolean DEFAULT false,
    redeemed_at timestamp without time zone,
    claimed_at timestamp with time zone,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone
);

--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying(255) NOT NULL,
    username character varying(255),
    email character varying(255),
    phone character varying(32),
    password character varying(255),
    email_verified_at timestamp with time zone,
    phone_verified_at timestamp with time zone,
    gender character varying(100),
    date_of_birth date,
    photo character varying(255),
    photo_public_id character varying(255),
    role_id uuid,
    status bigint DEFAULT 1 NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone
);

--
-- Name: vouchers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vouchers (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    code character varying(50),
    discount_amount bigint,
    discount_percent bigint,
    minimum_spend bigint,
    point_cost bigint,
    start_date timestamp without time zone,
    end_date timestamp without time zone,
    quota bigint,
    claimed_count bigint DEFAULT 0,
    description text,
    discount_type character varying(100),
    status bigint DEFAULT 0,
    created_by uuid,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone
);

--
-- Name: banners banners_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.banners
    ADD CONSTRAINT banners_pkey PRIMARY KEY (id);

--
-- Name: cart_items cart_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT cart_items_pkey PRIMARY KEY (id);

--
-- Name: carts carts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT carts_pkey PRIMARY KEY (id);

--
-- Name: customer_addresses customer_addresses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_addresses
    ADD CONSTRAINT customer_addresses_pkey PRIMARY KEY (id);

--
-- Name: event_bundle_buys event_bundle_buys_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_bundle_buys
    ADD CONSTRAINT event_bundle_buys_pkey PRIMARY KEY (id);

--
-- Name: event_bundle_rewards event_bundle_rewards_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_bundle_rewards
    ADD CONSTRAINT event_bundle_rewards_pkey PRIMARY KEY (id);

--
-- Name: event_products event_products_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_products
    ADD CONSTRAINT event_products_pkey PRIMARY KEY (id);

--
-- Name: events events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (id);

--
-- Name: favorite_items favorite_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorite_items
    ADD CONSTRAINT favorite_items_pkey PRIMARY KEY (id);

--
-- Name: favorites favorites_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorites
    ADD CONSTRAINT favorites_pkey PRIMARY KEY (id);

--
-- Name: images images_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.images
    ADD CONSTRAINT images_pkey PRIMARY KEY (id);

--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);

--
-- Name: order_events order_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_events
    ADD CONSTRAINT order_events_pkey PRIMARY KEY (id);

--
-- Name: order_items order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);

--
-- Name: order_rewards order_rewards_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_rewards
    ADD CONSTRAINT order_rewards_pkey PRIMARY KEY (id);

--
-- Name: order_vouchers order_vouchers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_vouchers
    ADD CONSTRAINT order_vouchers_pkey PRIMARY KEY (id);

--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);

--
-- Name: product_images product_images_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_images
    ADD CONSTRAINT product_images_pkey PRIMARY KEY (id);

--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);

--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);

--
-- Name: shop_cashiers shop_cashiers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shop_cashiers
    ADD CONSTRAINT shop_cashiers_pkey PRIMARY KEY (id);

--
-- Name: shop_images shop_images_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shop_images
    ADD CONSTRAINT shop_images_pkey PRIMARY KEY (id);

--
-- Name: shop_products shop_products_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shop_products
    ADD CONSTRAINT shop_products_pkey PRIMARY KEY (id);

--
-- Name: shops shops_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shops
    ADD CONSTRAINT shops_pkey PRIMARY KEY (id);

--
-- Name: type_products type_products_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.type_products
    ADD CONSTRAINT type_products_pkey PRIMARY KEY (id);

--
-- Name: roles uni_roles_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT uni_roles_name UNIQUE (name);

--
-- Name: user_identities user_identities_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_identities
    ADD CONSTRAINT user_identities_pkey PRIMARY KEY (id);

--
-- Name: user_point_histories user_point_histories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_point_histories
    ADD CONSTRAINT user_point_histories_pkey PRIMARY KEY (id);

--
-- Name: user_points user_points_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_points
    ADD CONSTRAINT user_points_pkey PRIMARY KEY (id);

--
-- Name: user_voucher_details user_voucher_details_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_voucher_details
    ADD CONSTRAINT user_voucher_details_pkey PRIMARY KEY (id);

--
-- Name: user_vouchers user_vouchers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_vouchers
    ADD CONSTRAINT user_vouchers_pkey PRIMARY KEY (id);

--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

--
-- Name: vouchers vouchers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vouchers
    ADD CONSTRAINT vouchers_pkey PRIMARY KEY (id);

--
-- Name: idx_banners_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_banners_deleted_at ON public.banners USING btree (deleted_at);

--
-- Name: idx_cart_items_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_cart_items_deleted_at ON public.cart_items USING btree (deleted_at);

--
-- Name: idx_carts_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_carts_deleted_at ON public.carts USING btree (deleted_at);

--
-- Name: idx_customer_addresses_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_customer_addresses_deleted_at ON public.customer_addresses USING btree (deleted_at);

--
-- Name: idx_event_bundle_buys_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_event_bundle_buys_deleted_at ON public.event_bundle_buys USING btree (deleted_at);

--
-- Name: idx_event_bundle_rewards_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_event_bundle_rewards_deleted_at ON public.event_bundle_rewards USING btree (deleted_at);

--
-- Name: idx_event_products_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_event_products_deleted_at ON public.event_products USING btree (deleted_at);

--
-- Name: idx_events_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_events_deleted_at ON public.events USING btree (deleted_at);

--
-- Name: idx_events_end_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_events_end_date ON public.events USING btree (end_date);

--
-- Name: idx_events_start_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_events_start_date ON public.events USING btree (start_date);

--
-- Name: idx_favorite_items_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_favorite_items_deleted_at ON public.favorite_items USING btree (deleted_at);

--
-- Name: idx_favorites_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_favorites_deleted_at ON public.favorites USING btree (deleted_at);

--
-- Name: idx_identity_provider_subject; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_identity_provider_subject ON public.user_identities USING btree (provider, subject);

--
-- Name: idx_images_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_images_deleted_at ON public.images USING btree (deleted_at);

--
-- Name: idx_images_image_path; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_images_image_path ON public.images USING btree (image_path);

--
-- Name: idx_images_public_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_images_public_id ON public.images USING btree (public_id);

--
-- Name: idx_notifications_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notifications_created_at ON public.notifications USING btree (created_at);

--
-- Name: idx_notifications_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notifications_deleted_at ON public.notifications USING btree (deleted_at);

--
-- Name: idx_notifications_read_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notifications_read_at ON public.notifications USING btree (read_at);

--
-- Name: idx_notifications_reference_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notifications_reference_id ON public.notifications USING btree (reference_id);

--
-- Name: idx_notifications_user_channel; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notifications_user_channel ON public.notifications USING btree (user_id, channel);

--
-- Name: idx_orders_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_orders_deleted_at ON public.orders USING btree (deleted_at);

--
-- Name: idx_product_images_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_product_images_deleted_at ON public.product_images USING btree (deleted_at);

--
-- Name: idx_product_images_image_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_product_images_image_id ON public.product_images USING btree (image_id);

--
-- Name: idx_product_images_product_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_product_images_product_id ON public.product_images USING btree (product_id);

--
-- Name: idx_products_code; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_products_code ON public.products USING btree (code);

--
-- Name: idx_products_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_products_deleted_at ON public.products USING btree (deleted_at);

--
-- Name: idx_products_image_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_products_image_id ON public.products USING btree (image_id);

--
-- Name: idx_products_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_products_name ON public.products USING btree (name);

--
-- Name: idx_products_type_product_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_products_type_product_id ON public.products USING btree (type_product_id);

--
-- Name: idx_shop_cashiers_cashier_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_shop_cashiers_cashier_id ON public.shop_cashiers USING btree (cashier_id);

--
-- Name: idx_shop_cashiers_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_shop_cashiers_deleted_at ON public.shop_cashiers USING btree (deleted_at);

--
-- Name: idx_shop_cashiers_shop_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_shop_cashiers_shop_id ON public.shop_cashiers USING btree (shop_id);

--
-- Name: idx_shop_images_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_shop_images_deleted_at ON public.shop_images USING btree (deleted_at);

--
-- Name: idx_shop_products_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_shop_products_deleted_at ON public.shop_products USING btree (deleted_at);

--
-- Name: idx_shop_products_shop_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_shop_products_shop_id ON public.shop_products USING btree (shop_id);

--
-- Name: idx_shops_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_shops_deleted_at ON public.shops USING btree (deleted_at);

--
-- Name: idx_type_products_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_type_products_deleted_at ON public.type_products USING btree (deleted_at);

--
-- Name: idx_user_identities_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_identities_user_id ON public.user_identities USING btree (user_id);

--
-- Name: idx_user_point_histories_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_point_histories_deleted_at ON public.user_point_histories USING btree (deleted_at);

--
-- Name: idx_user_point_histories_expired_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_point_histories_expired_at ON public.user_point_histories USING btree (expired_at);

--
-- Name: idx_user_point_histories_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_point_histories_user_id ON public.user_point_histories USING btree (user_id);

--
-- Name: idx_user_points_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_points_deleted_at ON public.user_points USING btree (deleted_at);

--
-- Name: idx_user_points_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_user_points_user_id ON public.user_points USING btree (user_id);

--
-- Name: idx_user_voucher_details_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_voucher_details_deleted_at ON public.user_voucher_details USING btree (deleted_at);

--
-- Name: idx_user_vouchers_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_vouchers_deleted_at ON public.user_vouchers USING btree (deleted_at);

--
-- Name: idx_user_vouchers_detail_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_vouchers_detail_id ON public.user_vouchers USING btree (detail_id);

--
-- Name: idx_user_vouchers_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_vouchers_user_id ON public.user_vouchers USING btree (user_id);

--
-- Name: idx_user_vouchers_voucher_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_vouchers_voucher_id ON public.user_vouchers USING btree (voucher_id);

--
-- Name: idx_users_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_deleted_at ON public.users USING btree (deleted_at);

--
-- Name: idx_users_email; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_users_email ON public.users USING btree (email);

--
-- Name: idx_users_email_verified_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_email_verified_at ON public.users USING btree (email_verified_at);

--
-- Name: idx_users_phone; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_users_phone ON public.users USING btree (phone);

--
-- Name: idx_users_phone_verified_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_phone_verified_at ON public.users USING btree (phone_verified_at);

--
-- Name: idx_users_role_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_role_id ON public.users USING btree (role_id);

--
-- Name: idx_users_username; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_users_username ON public.users USING btree (username);

--
-- Name: idx_vouchers_code; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_vouchers_code ON public.vouchers USING btree (code);

--
-- Name: idx_vouchers_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_vouchers_deleted_at ON public.vouchers USING btree (deleted_at);

--
-- Name: idx_vouchers_end_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_vouchers_end_date ON public.vouchers USING btree (end_date);

--
-- Name: idx_vouchers_start_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_vouchers_start_date ON public.vouchers USING btree (start_date);

--
-- Name: banners fk_banners_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.banners
    ADD CONSTRAINT fk_banners_user FOREIGN KEY (user_id) REFERENCES public.users(id);

--
-- Name: cart_items fk_cart_items_cart; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT fk_cart_items_cart FOREIGN KEY (cart_id) REFERENCES public.carts(id);

--
-- Name: cart_items fk_cart_items_product; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT fk_cart_items_product FOREIGN KEY (product_id) REFERENCES public.products(id);

--
-- Name: carts fk_carts_shop; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT fk_carts_shop FOREIGN KEY (shop_id) REFERENCES public.shops(id) ON DELETE CASCADE;

--
-- Name: carts fk_carts_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT fk_carts_user FOREIGN KEY (user_id) REFERENCES public.users(id);

--
-- Name: customer_addresses fk_customer_addresses_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_addresses
    ADD CONSTRAINT fk_customer_addresses_user FOREIGN KEY (user_id) REFERENCES public.users(id);

--
-- Name: event_bundle_buys fk_event_bundle_buys_event; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_bundle_buys
    ADD CONSTRAINT fk_event_bundle_buys_event FOREIGN KEY (event_id) REFERENCES public.events(id);

--
-- Name: event_bundle_buys fk_event_bundle_buys_product; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_bundle_buys
    ADD CONSTRAINT fk_event_bundle_buys_product FOREIGN KEY (product_id) REFERENCES public.products(id);

--
-- Name: event_bundle_rewards fk_event_bundle_rewards_event; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_bundle_rewards
    ADD CONSTRAINT fk_event_bundle_rewards_event FOREIGN KEY (event_id) REFERENCES public.events(id);

--
-- Name: event_bundle_rewards fk_event_bundle_rewards_product; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_bundle_rewards
    ADD CONSTRAINT fk_event_bundle_rewards_product FOREIGN KEY (product_id) REFERENCES public.products(id);

--
-- Name: event_products fk_event_products_event; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_products
    ADD CONSTRAINT fk_event_products_event FOREIGN KEY (event_id) REFERENCES public.events(id);

--
-- Name: event_products fk_event_products_product; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_products
    ADD CONSTRAINT fk_event_products_product FOREIGN KEY (product_id) REFERENCES public.products(id);

--
-- Name: events fk_events_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT fk_events_user FOREIGN KEY (created_by) REFERENCES public.users(id);

--
-- Name: favorite_items fk_favorite_items_favorite; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorite_items
    ADD CONSTRAINT fk_favorite_items_favorite FOREIGN KEY (favorite_id) REFERENCES public.favorites(id);

--
-- Name: favorite_items fk_favorite_items_product; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorite_items
    ADD CONSTRAINT fk_favorite_items_product FOREIGN KEY (product_id) REFERENCES public.products(id);

--
-- Name: favorites fk_favorites_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorites
    ADD CONSTRAINT fk_favorites_user FOREIGN KEY (user_id) REFERENCES public.users(id);

--
-- Name: notifications fk_notifications_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES public.users(id);

--
-- Name: order_events fk_order_events_event; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_events
    ADD CONSTRAINT fk_order_events_event FOREIGN KEY (event_id) REFERENCES public.events(id);

--
-- Name: order_events fk_order_events_order; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_events
    ADD CONSTRAINT fk_order_events_order FOREIGN KEY (order_id) REFERENCES public.orders(id);

--
-- Name: order_items fk_order_items_order; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES public.orders(id);

--
-- Name: order_items fk_order_items_product; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES public.products(id);

--
-- Name: order_rewards fk_order_rewards_order; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_rewards
    ADD CONSTRAINT fk_order_rewards_order FOREIGN KEY (order_id) REFERENCES public.orders(id);

--
-- Name: order_rewards fk_order_rewards_product; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_rewards
    ADD CONSTRAINT fk_order_rewards_product FOREIGN KEY (product_id) REFERENCES public.products(id);

--
-- Name: order_vouchers fk_order_vouchers_order; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_vouchers
    ADD CONSTRAINT fk_order_vouchers_order FOREIGN KEY (order_id) REFERENCES public.orders(id);

--
-- Name: order_vouchers fk_order_vouchers_voucher; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_vouchers
    ADD CONSTRAINT fk_order_vouchers_voucher FOREIGN KEY (voucher_id) REFERENCES public.vouchers(id);

--
-- Name: orders fk_orders_cart; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk_orders_cart FOREIGN KEY (cart_id) REFERENCES public.carts(id);

--
-- Name: orders fk_orders_customer_address; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk_orders_customer_address FOREIGN KEY (customer_address_id) REFERENCES public.customer_addresses(id);

--
-- Name: orders fk_orders_shop; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk_orders_shop FOREIGN KEY (shop_id) REFERENCES public.shops(id);

--
-- Name: orders fk_orders_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES public.users(id);

--
-- Name: product_images fk_product_images_image; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_images
    ADD CONSTRAINT fk_product_images_image FOREIGN KEY (image_id) REFERENCES public.images(id);

--
-- Name: products fk_products_image; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fk_products_image FOREIGN KEY (image_id) REFERENCES public.images(id);

--
-- Name: product_images fk_products_product_images; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_images
    ADD CONSTRAINT fk_products_product_images FOREIGN KEY (product_id) REFERENCES public.products(id);

--
-- Name: products fk_products_type_product; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fk_products_type_product FOREIGN KEY (type_product_id) REFERENCES public.type_products(id);

--
-- Name: products fk_products_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fk_products_user FOREIGN KEY (created_by) REFERENCES public.users(id);

--
-- Name: shop_cashiers fk_shop_cashiers_shop; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shop_cashiers
    ADD CONSTRAINT fk_shop_cashiers_shop FOREIGN KEY (shop_id) REFERENCES public.shops(id);

--
-- Name: shop_cashiers fk_shop_cashiers_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shop_cashiers
    ADD CONSTRAINT fk_shop_cashiers_user FOREIGN KEY (cashier_id) REFERENCES public.users(id);

--
-- Name: shop_images fk_shop_images_image; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shop_images
    ADD CONSTRAINT fk_shop_images_image FOREIGN KEY (image_id) REFERENCES public.images(id);

--
-- Name: shop_images fk_shop_images_shop; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shop_images
    ADD CONSTRAINT fk_shop_images_shop FOREIGN KEY (shop_id) REFERENCES public.shops(id);

--
-- Name: shop_products fk_shop_products_product; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shop_products
    ADD CONSTRAINT fk_shop_products_product FOREIGN KEY (product_id) REFERENCES public.products(id);

--
-- Name: shop_products fk_shop_products_shop; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shop_products
    ADD CONSTRAINT fk_shop_products_shop FOREIGN KEY (shop_id) REFERENCES public.shops(id);

--
-- Name: shops fk_shops_creator; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shops
    ADD CONSTRAINT fk_shops_creator FOREIGN KEY (created_by) REFERENCES public.users(id);

--
-- Name: type_products fk_type_products_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.type_products
    ADD CONSTRAINT fk_type_products_user FOREIGN KEY (user_id) REFERENCES public.users(id);

--
-- Name: user_point_histories fk_user_point_histories_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_point_histories
    ADD CONSTRAINT fk_user_point_histories_user FOREIGN KEY (user_id) REFERENCES public.users(id);

--
-- Name: user_points fk_user_points_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_points
    ADD CONSTRAINT fk_user_points_user FOREIGN KEY (user_id) REFERENCES public.users(id);

--
-- Name: user_vouchers fk_user_vouchers_detail; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_vouchers
    ADD CONSTRAINT fk_user_vouchers_detail FOREIGN KEY (detail_id) REFERENCES public.user_voucher_details(id);

--
-- Name: user_vouchers fk_user_vouchers_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_vouchers
    ADD CONSTRAINT fk_user_vouchers_user FOREIGN KEY (user_id) REFERENCES public.users(id);

--
-- Name: user_vouchers fk_user_vouchers_voucher; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_vouchers
    ADD CONSTRAINT fk_user_vouchers_voucher FOREIGN KEY (voucher_id) REFERENCES public.vouchers(id);

--
-- Name: user_identities fk_users_identities; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_identities
    ADD CONSTRAINT fk_users_identities FOREIGN KEY (user_id) REFERENCES public.users(id);

--
-- Name: users fk_users_role; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES public.roles(id);

--
-- Name: vouchers fk_vouchers_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vouchers
    ADD CONSTRAINT fk_vouchers_user FOREIGN KEY (created_by) REFERENCES public.users(id);

--
-- PostgreSQL database dump complete
--
